uploads = []
outputs = []

[[generated]]
id = "V--bkKUQ8Kxn4JlIbly2w"
uri = "file://artifacts/xf-store/public/images/product-hoodie-white.png"
type = "image"
title = "white hoodie front"

[[generated]]
id = "1FL-nCvquYPowBffCAsx6"
uri = "file://artifacts/xf-store/public/images/product-tee-grey.png"
type = "image"
title = "grey tee product"

[[generated]]
id = "jlfyT9vd1m_GE2P48fFeB"
uri = "file://artifacts/xf-store/public/images/product-jogger-white.png"
type = "image"
title = "white jogger product"

[[generated]]
id = "4qO52ZkTsRrtcUAtTBxps"
uri = "file://artifacts/xf-store/public/images/product-hoodie-white-back.png"
type = "image"
title = "white hoodie back"

[[generated]]
id = "9jfWPta7vBaDcFr5VwJFV"
uri = "file://artifacts/xf-store/public/images/product-hoodie-black-flat.png"
type = "image"
title = "black hoodie flat lay"

[[generated]]
id = "ZFlQ531GGVNM8tJfaP2Yz"
uri = "file://artifacts/xf-store/public/images/product-hoodie-grey-flat.png"
type = "image"
title = "grey hoodie flat lay"

[[generated]]
id = "xV6ZC1wYIBnOVKVh2WQ61"
uri = "file://artifacts/xf-store/public/images/product-hoodie-white-flat.png"
type = "image"
title = "white hoodie flat lay"

[[generated]]
id = "lHS61XHqshQcRLlb_XrVN"
uri = "file://artifacts/xf-store/public/images/product-tee-black-back.png"
type = "image"
title = "black tee back"

[[generated]]
id = "JMVfhTIkifgIHdlGWy9qb"
uri = "file://artifacts/xf-store/public/images/product-tee-grey-back.png"
type = "image"
title = "grey tee back"

[[generated]]
id = "FJ7g5WFttQPS5xleqdcmz"
uri = "file://artifacts/xf-store/public/images/product-tee-white-back.png"
type = "image"
title = "white tee back"

[[generated]]
id = "3WUXZpDWFMsExQXVn-aVO"
uri = "file://artifacts/xf-store/public/images/product-jogger-black-flat.png"
type = "image"
title = "black jogger flat lay"

[[generated]]
id = "IuU_jD4T61eXkzj75CgQr"
uri = "file://artifacts/xf-store/public/images/product-jogger-grey-flat.png"
type = "image"
title = "grey jogger flat lay"

[[generated]]
id = "r8Xue3F73XFvg41MqThHI"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhemm-black.png"
type = "image"
title = "black open hem jogger"

[[generated]]
id = "1puFRn8mu5e149xN2last"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhem-grey.png"
type = "image"
title = "grey open hem jogger"

[[generated]]
id = "T4gu7qNTkpoc-UV-d-zAW"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhem-white.png"
type = "image"
title = "white open hem jogger"

[[generated]]
id = "j63jrFMNxjfwZEGAKVHvy"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhem-black-flat.png"
type = "image"
title = "black open hem jogger flat"

[[generated]]
id = "AKoZnP518aJ9fejkIVlbU"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhem-grey-flat.png"
type = "image"
title = "grey open hem jogger flat"

[[generated]]
id = "gY93psIQFzYwaDULid6o0"
uri = "file://artifacts/xf-store/public/images/product-jogger-openhem-white-flat.png"
type = "image"
title = "white open hem jogger flat"
